apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rku-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: rku
    spec:
      containers:
      - name: rku
        image: gcr.io/study-161802/rku:latest
        resources:
          request:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "96Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_ENV
          value: "production"
        - name: DBPASS
          value: "quizmtv12"
        - name: SECRET_KEY_BASE
          value: "102ec6ddfd98f662f6e750e7f746a62c8017ba841dfb3197b1d937e2f37be2ce2d10b457b1fa1a49aac2e849ce39396ced712d40ec02d9cf68e96f7459208fbb"