apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rku-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: rku
    spec:
      containers:
      - name: rku
        # Image version is latest when manually deploying, but when deploying it will be rku:${CIRCLE_BUILD_NUM}
        image: gcr.io/study-161802/rku:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_ENV
          value: "${RAILS_ENV}"
        - name: DBPASS
          value: "${DBPASS}"
        - name: SECRET_KEY_BASE
          value: "${SECRET_KEY_BASE}"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # A minimum of 70% of the pods will be available while performing 0 downtime deploy
      maxUnavailable: "30%"